#include "cs2dumper/output.hpp"

#include <algorithm>
#include <chrono>
#include <cctype>
#include <cstdint>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <map>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>

namespace cs2dumper {
namespace {

class Formatter {
public:
    explicit Formatter(std::size_t indent_size) : indent_size_(indent_size) {}

    void line(std::string_view s = {}) {
        if (s.empty()) { out_ << '\n'; return; }
        std::size_t begin = 0;
        while (begin <= s.size()) {
            const auto end = s.find('\n', begin);
            const auto part = s.substr(begin, end == std::string_view::npos ? s.size() - begin : end - begin);
            if (!part.empty()) out_ << std::string(level_ * indent_size_, ' ') << part;
            out_ << '\n';
            if (end == std::string_view::npos) break;
            begin = end + 1;
        }
    }

    void raw(std::string_view s) { out_ << s; }

    template <typename F>
    void block(const std::string& heading, bool semicolon, F&& fn) {
        line(heading + " {");
        ++level_;
        fn();
        --level_;
        line(semicolon ? "};" : "}");
    }

    [[nodiscard]] std::string str() const { return out_.str(); }

private:
    std::ostringstream out_;
    std::size_t indent_size_{};
    std::size_t level_{};
};

std::string hex(std::int64_t value) {
    std::ostringstream ss;
    ss << "0x" << std::uppercase << std::hex << static_cast<std::uint64_t>(value);
    return ss.str();
}

std::string json_escape(std::string_view s) {
    std::ostringstream out;
    for (unsigned char c : s) {
        switch (c) {
        case '"': out << "\\\""; break;
        case '\\': out << "\\\\"; break;
        case '\b': out << "\\b"; break;
        case '\f': out << "\\f"; break;
        case '\n': out << "\\n"; break;
        case '\r': out << "\\r"; break;
        case '\t': out << "\\t"; break;
        default:
            if (c < 0x20) {
                out << "\\u" << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(c) << std::dec;
            } else {
                out << static_cast<char>(c);
            }
        }
    }
    return out.str();
}

std::string q(std::string_view s) { return "\"" + json_escape(s) + "\""; }

std::string snake_case(std::string s) {
    std::string out;
    for (std::size_t i = 0; i < s.size(); ++i) {
        const char c = s[i];
        if (std::isupper(static_cast<unsigned char>(c))) {
            if (i && !out.empty() && out.back() != '_') out.push_back('_');
            out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
        } else {
            out.push_back(c);
        }
    }
    return out;
}

std::string utc_timestamp(bool banner) {
    const auto now = std::chrono::system_clock::now();
    const auto tt = std::chrono::system_clock::to_time_t(now);
    std::tm tm{};
#ifdef _WIN32
    gmtime_s(&tm, &tt);
#else
    gmtime_r(&tt, &tm);
#endif
    std::ostringstream ss;
    if (banner) ss << std::put_time(&tm, "%Y-%m-%d %H:%M:%S UTC");
    else ss << std::put_time(&tm, "%Y-%m-%dT%H:%M:%SZ");
    return ss.str();
}

void write_file(const std::filesystem::path& path, const std::string& data) {
    std::ofstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("unable to open output file: " + path.string());
    f.write(data.data(), static_cast<std::streamsize>(data.size()));
}

void banner(Formatter& f, const std::string& timestamp) {
    f.line("// Generated by cs2-dumper-cpp-standalone");
    f.line("// " + timestamp);
    f.line();
}

void write_metadata(Formatter& f, const std::vector<ClassMetadata>& metadata) {
    if (metadata.empty()) return;
    f.line("// Metadata:");
    for (const auto& m : metadata) {
        switch (m.kind) {
        case ClassMetadataKind::NetworkChangeCallback:
            f.line("// NetworkChangeCallback: " + m.name);
            break;
        case ClassMetadataKind::NetworkVarNames:
            f.line("// NetworkVarNames: " + m.name + " (" + m.type_name + ")");
            break;
        case ClassMetadataKind::Unknown:
            f.line("// " + m.name);
            break;
        }
    }
}

std::string buttons_json(const ButtonMap& map) {
    Formatter f(2);
    f.raw("{\n  \"client.dll\": {");
    bool first = true;
    for (const auto& [name, value] : map) {
        f.raw(first ? "\n" : ",\n");
        first = false;
        f.raw("    " + q(name) + ": " + std::to_string(value));
    }
    if (!map.empty()) f.raw("\n");
    f.raw("  }\n}");
    return f.str();
}

std::string buttons_hpp(const ButtonMap& map, std::size_t indent, const std::string& timestamp) {
    Formatter f(indent);
    banner(f, timestamp);
    f.line("#pragma once");
    f.line();
    f.line("#include <cstddef>");
    f.line();
    f.block("namespace cs2_dumper", false, [&] {
        f.block("namespace buttons", false, [&] {
            for (const auto& [name, value] : map) {
                f.line("inline constexpr std::ptrdiff_t " + slugify(name) + " = " + hex(value) + ";");
            }
        });
    });
    return f.str();
}

std::string nested_json(const std::map<std::string, std::map<std::string, std::uint64_t>>& map) {
    Formatter f(2);
    f.raw("{");
    bool fm = true;
    for (const auto& [module, values] : map) {
        f.raw(fm ? "\n" : ",\n");
        fm = false;
        f.raw("  " + q(module) + ": {");
        bool fv = true;
        for (const auto& [name, value] : values) {
            f.raw(fv ? "\n" : ",\n");
            fv = false;
            f.raw("    " + q(name) + ": " + std::to_string(value));
        }
        if (!values.empty()) f.raw("\n");
        f.raw("  }");
    }
    if (!map.empty()) f.raw("\n");
    f.raw("}");
    return f.str();
}

std::string offsets_json(const OffsetMap& map) {
    std::map<std::string, std::map<std::string, std::uint64_t>> wide;
    for (const auto& [module, values] : map) {
        for (const auto& [name, value] : values) wide[module][name] = value;
    }
    return nested_json(wide);
}

std::string nested_hpp(const std::map<std::string, std::map<std::string, std::uint64_t>>& map,
                       const std::string& root_name, std::size_t indent, const std::string& timestamp) {
    Formatter f(indent);
    banner(f, timestamp);
    f.line("#pragma once");
    f.line();
    f.line("#include <cstddef>");
    f.line("#include <cstdint>");
    f.line();
    f.block("namespace cs2_dumper", false, [&] {
        f.block("namespace " + root_name, false, [&] {
            for (const auto& [module, values] : map) {
                f.line("// Module: " + module);
                f.block("namespace " + snake_case(slugify(module)), false, [&] {
                    for (const auto& [name, value] : values) {
                        f.line("inline constexpr std::uintptr_t " + slugify(name) + " = " + hex(static_cast<std::int64_t>(value)) + ";");
                    }
                });
            }
        });
    });
    return f.str();
}

std::string offsets_hpp(const OffsetMap& map, std::size_t indent, const std::string& timestamp) {
    std::map<std::string, std::map<std::string, std::uint64_t>> wide;
    for (const auto& [module, values] : map) {
        for (const auto& [name, value] : values) wide[module][name] = value;
    }
    return nested_hpp(wide, "offsets", indent, timestamp);
}

std::string enum_cpp_type(std::uint8_t alignment) {
    if (alignment == 1) return "std::uint8_t";
    if (alignment == 2) return "std::uint16_t";
    if (alignment == 4) return "std::uint32_t";
    if (alignment == 8) return "std::uint64_t";
    return {};
}

std::string enum_hex(std::int64_t value, std::uint8_t alignment) {
    std::uint64_t narrowed{};
    switch (alignment) {
    case 1:
        narrowed = static_cast<std::uint8_t>(value);
        break;
    case 2:
        narrowed = static_cast<std::uint16_t>(value);
        break;
    case 4:
        narrowed = static_cast<std::uint32_t>(value);
        break;
    case 8:
        narrowed = static_cast<std::uint64_t>(value);
        break;
    default:
        narrowed = static_cast<std::uint64_t>(value);
        break;
    }

    std::ostringstream ss;
    ss << "0x" << std::uppercase << std::hex << narrowed;
    return ss.str();
}

std::string schemas_json(const SchemaMap& map) {
    Formatter f(2);
    f.raw("{\n");
    bool fm = true;
    for (const auto& [module, pair] : map) {
        if (!fm) f.raw(",\n");
        fm = false;
        const auto& classes = pair.first;
        const auto& enums = pair.second;
        f.raw("  " + q(module) + ": {\n    \"classes\": {");
        bool fc = true;
        for (const auto& cls : classes) {
            if (!fc) f.raw(",");
            fc = false;
            f.raw("\n      " + q(cls.name) + ": {\n");
            f.raw("        \"parent\": " + (cls.parent_name ? q(*cls.parent_name) : "null") + ",\n");
            f.raw("        \"fields\": {");
            std::map<std::string, std::int32_t> sorted_fields;
            for (const auto& field : cls.fields) sorted_fields[field.name] = field.offset;
            bool ff = true;
            for (const auto& [name, off] : sorted_fields) {
                if (!ff) f.raw(",");
                ff = false;
                f.raw("\n          " + q(name) + ": " + std::to_string(off));
            }
            if (!sorted_fields.empty()) f.raw("\n        ");
            f.raw("},\n        \"metadata\": [");
            for (std::size_t i = 0; i < cls.metadata.size(); ++i) {
                const auto& md = cls.metadata[i];
                if (i) f.raw(",");
                const char* kind = md.kind == ClassMetadataKind::NetworkChangeCallback ? "NetworkChangeCallback" :
                                   md.kind == ClassMetadataKind::NetworkVarNames ? "NetworkVarNames" : "Unknown";
                f.raw("\n          {\"type\": " + q(kind) + ", \"name\": " + q(md.name));
                if (md.kind == ClassMetadataKind::NetworkVarNames) f.raw(", \"type_name\": " + q(md.type_name));
                f.raw("}");
            }
            if (!cls.metadata.empty()) f.raw("\n        ");
            f.raw("]\n      }");
        }
        if (!classes.empty()) f.raw("\n    ");
        f.raw("},\n    \"enums\": {");
        bool fe = true;
        for (const auto& en : enums) {
            if (!fe) f.raw(",");
            fe = false;
            f.raw("\n      " + q(en.name) + ": {\n");
            f.raw("        \"alignment\": " + std::to_string(en.alignment) + ",\n");
            f.raw("        \"members\": {");
            bool member_first = true;
            for (const auto& member : en.members) {
                if (!member_first) f.raw(",");
                member_first = false;
                f.raw("\n          " + q(member.name) + ": " + std::to_string(member.value));
            }
            if (!en.members.empty()) f.raw("\n        ");
            f.raw("}\n      }");
        }
        if (!enums.empty()) f.raw("\n    ");
        f.raw("}\n  }");
    }
    f.raw("\n}");
    return f.str();
}

std::string schemas_hpp(const SchemaMap& map, std::size_t indent, const std::string& timestamp) {
    Formatter f(indent);
    banner(f, timestamp);
    f.line("#pragma once");
    f.line();
    f.line("#include <cstddef>");
    f.line("#include <cstdint>");
    f.line();
    f.block("namespace cs2_dumper", false, [&] {
        f.block("namespace schemas", false, [&] {
            for (const auto& [module, pair] : map) {
                const auto& classes = pair.first;
                const auto& enums = pair.second;
                f.line("// Module: " + module);
                f.line("// Class count: " + std::to_string(classes.size()));
                f.line("// Enum count: " + std::to_string(enums.size()));
                f.block("namespace " + snake_case(slugify(module)), false, [&] {
                    for (const auto& en : enums) {
                        const auto type = enum_cpp_type(en.alignment);
                        if (type.empty()) continue;
                        f.line("// Alignment: " + std::to_string(en.alignment));
                        f.block("enum class " + slugify(en.name) + " : " + type, true, [&] {
                            for (const auto& member : en.members) {
                                f.line(slugify(member.name) + " = " + enum_hex(member.value, en.alignment) + ",");
                            }
                        });
                    }
                    for (const auto& cls : classes) {
                        f.line("// Parent: " + (cls.parent_name ? *cls.parent_name : "None"));
                        write_metadata(f, cls.metadata);
                        f.block("namespace " + slugify(cls.name), false, [&] {
                            for (const auto& field : cls.fields) {
                                f.line("inline constexpr std::ptrdiff_t " + slugify(field.name) + " = " +
                                       hex(field.offset) + "; // " + field.type_name);
                            }
                        });
                    }
                });
            }
        });
    });
    return f.str();
}

} // namespace

std::string slugify(std::string input) {
    for (char& c : input) {
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') c = '_';
    }
    if (input.empty() || std::isdigit(static_cast<unsigned char>(input.front()))) input.insert(input.begin(), '_');
    return input;
}

Output::Output(std::vector<std::string> file_types, std::size_t indent_size,
               std::filesystem::path out_dir, const AnalysisResult& result)
    : file_types_(std::move(file_types)), indent_size_(indent_size), out_dir_(std::move(out_dir)), result_(result),
      timestamp_rfc3339_(utc_timestamp(false)), timestamp_banner_(utc_timestamp(true)) {
    std::filesystem::create_directories(out_dir_);
}

void Output::dump_all(IProcessMemory& process) const {
    for (const auto& type : file_types_) {
        if (type == "hpp") {
            write_file(out_dir_ / "buttons.hpp", buttons_hpp(result_.buttons, indent_size_, timestamp_banner_));
            write_file(out_dir_ / "interfaces.hpp", nested_hpp(result_.interfaces, "interfaces", indent_size_, timestamp_banner_));
            write_file(out_dir_ / "offsets.hpp", offsets_hpp(result_.offsets, indent_size_, timestamp_banner_));
        } else if (type == "json") {
            write_file(out_dir_ / "buttons.json", buttons_json(result_.buttons));
            write_file(out_dir_ / "interfaces.json", nested_json(result_.interfaces));
            write_file(out_dir_ / "offsets.json", offsets_json(result_.offsets));
        } else {
            throw std::runtime_error("unsupported output type: " + type);
        }
    }

    for (const auto& [module, pair] : result_.schemas) {
        const SchemaMap one{{module, pair}};
        for (const auto& type : file_types_) {
            if (type == "hpp") write_file(out_dir_ / (slugify(module) + ".hpp"), schemas_hpp(one, indent_size_, timestamp_banner_));
            else if (type == "json") write_file(out_dir_ / (slugify(module) + ".json"), schemas_json(one));
        }
    }

    std::optional<std::uint32_t> build;
    for (const auto& [module_name, offsets] : result_.offsets) {
        const auto it = offsets.find("dwBuildNumber");
        if (it == offsets.end()) continue;
        try {
            const auto module = process.module_by_name(module_name);
            build = process.read<std::uint32_t>(module.base + it->second);
            break;
        } catch (...) {}
    }

    std::string info = "{\n  \"timestamp\": " + q(timestamp_rfc3339_);
    if (build) info += ",\n  \"build_number\": " + std::to_string(*build);
    else info += ",\n  \"build_number\": null";
    info += "\n}";
    write_file(out_dir_ / "info.json", info);
}

} // namespace cs2dumper
